<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>JonStats - Introduction to Generalised Linear Models</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="../../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../../">
<script src="../../../site_libs/quarto-html/quarto.js"></script>
<script src="../../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../../../site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="../../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../../../site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="../../../site_libs/quarto-diagram/mermaid.min.js"></script>
<script src="../../../site_libs/quarto-diagram/mermaid-init.js"></script>
<link href="../../../site_libs/quarto-diagram/mermaid.css" rel="stylesheet">

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="../../../styles.css">
</head>

<body class="nav-sidebar floating nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../../../index.html">
    <span class="navbar-title">JonStats</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../../index.html" rel="" target="">
 <span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../about.html" rel="" target="">
 <span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-main-course-statistical-inference-and-simulation" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
 <span class="menu-text">Main Course: Statistical Inference and Simulation</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-main-course-statistical-inference-and-simulation">    
        <li>
    <a class="dropdown-item" href="../../../pages/main-course/intro-to-glms/index.html" rel="" target="">
 <span class="dropdown-text">(1) Intro to GLMs</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../pages/main-course/likelihood-and-simulation-theory/index.html" rel="" target="">
 <span class="dropdown-text">(2) Likelihood and Simulation Theory</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../pages/main-course/complete-simulation-example/index.html" rel="" target="">
 <span class="dropdown-text">(3) Complete Simulation Example</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-supplementary-courses" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
 <span class="menu-text">Supplementary Courses</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-supplementary-courses">    
        <li>
    <a class="dropdown-item" href="../../../pages/extra-courses/causal-inference/index.html" rel="" target="">
 <span class="dropdown-text">Causal Inference</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../pages/extra-courses/time-series/index.html" rel="" target="">
 <span class="dropdown-text">Time Series</span></a>
  </li>  
    </ul>
  </li>
</ul>
            <div class="quarto-navbar-tools ms-auto">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../../pages/main-course/intro-to-glms/index.html">(1) Intro to GLMs</a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto">
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../pages/main-course/intro-to-glms/index.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">(1) Intro to GLMs</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../pages/main-course/likelihood-and-simulation-theory/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">(2) Likelihood and Simulation Theory</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../pages/main-course/complete-simulation-example/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">(3) Complete Simulation Example</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#aim" id="toc-aim" class="nav-link active" data-scroll-target="#aim">Aim</a></li>
  <li><a href="#what-are-statistical-models-and-how-are-they-fit" id="toc-what-are-statistical-models-and-how-are-they-fit" class="nav-link" data-scroll-target="#what-are-statistical-models-and-how-are-they-fit">What are statistical models and how are they fit?</a></li>
  <li><a href="#systematic-components-and-link-functions" id="toc-systematic-components-and-link-functions" class="nav-link" data-scroll-target="#systematic-components-and-link-functions">Systematic components and link functions</a></li>
  <li><a href="#how-to-express-a-linear-model-as-a-generalised-linear-model" id="toc-how-to-express-a-linear-model-as-a-generalised-linear-model" class="nav-link" data-scroll-target="#how-to-express-a-linear-model-as-a-generalised-linear-model">How to express a linear model as a generalised linear model</a></li>
  <li><a href="#why-only-betas-look-at-betas" id="toc-why-only-betas-look-at-betas" class="nav-link" data-scroll-target="#why-only-betas-look-at-betas">Why only betas look at betas</a>
  <ul class="collapse">
  <li><a href="#why-overuse-of-linear-regression-leads-people-to-look-at-models-in-the-wrong-way" id="toc-why-overuse-of-linear-regression-leads-people-to-look-at-models-in-the-wrong-way" class="nav-link" data-scroll-target="#why-overuse-of-linear-regression-leads-people-to-look-at-models-in-the-wrong-way">Why overuse of linear regression leads people to look at models in the wrong way</a></li>
  <li><a href="#linear-regression-example" id="toc-linear-regression-example" class="nav-link" data-scroll-target="#linear-regression-example">Linear Regression example</a></li>
  <li><a href="#logistic-regression-example" id="toc-logistic-regression-example" class="nav-link" data-scroll-target="#logistic-regression-example">Logistic Regression example</a></li>
  <li><a href="#dont-stargaze" id="toc-dont-stargaze" class="nav-link" data-scroll-target="#dont-stargaze">(Don’t) Stargaze</a></li>
  <li><a href="#standardisation" id="toc-standardisation" class="nav-link" data-scroll-target="#standardisation">Standardisation</a></li>
  <li><a href="#maximum-marginal-effects-divide-by-four" id="toc-maximum-marginal-effects-divide-by-four" class="nav-link" data-scroll-target="#maximum-marginal-effects-divide-by-four">Maximum marginal effects: Divide-by-four</a></li>
  <li><a href="#predictions-on-a-matrix" id="toc-predictions-on-a-matrix" class="nav-link" data-scroll-target="#predictions-on-a-matrix">Predictions on a matrix</a></li>
  <li><a href="#marginal-effects-on-observed-data" id="toc-marginal-effects-on-observed-data" class="nav-link" data-scroll-target="#marginal-effects-on-observed-data">Marginal effects on observed data</a></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion">Conclusion</a></li>
  </ul></li>
  <li><a href="#page-discussion" id="toc-page-discussion" class="nav-link" data-scroll-target="#page-discussion">Page discussion</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Introduction to Generalised Linear Models</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<section id="aim" class="level2">
<h2 class="anchored" data-anchor-id="aim">Aim</h2>
<p>The aims of this web page is to provide an overview of generalised linear models, and ways of thinking about modelling that go beyond ‘star-gazing’.</p>
</section>
<section id="what-are-statistical-models-and-how-are-they-fit" class="level2">
<h2 class="anchored" data-anchor-id="what-are-statistical-models-and-how-are-they-fit">What are statistical models and how are they fit?</h2>
<p>It’s common for different statistical methods to be taught as if they’re completely different species or families. In particular, for standard linear regression to be taught first, then additional, more exotic models, like logistic or Poisson regression, to be introduced at a later stage, in an advanced course.</p>
<p>The disadvantage with this standard approach to teaching statistics is that it obscures the way that almost all statistical models are, fundamentally, trying to do something very similar, and work in very similar ways.</p>
<p>Something I’ve found immensely helpful over the years is the following pair of equations:</p>
<p><strong>Stochastic Component</strong></p>
<p><span class="math display">\[
Y_i \sim f(\theta_i, \alpha)
\]</span></p>
<p><strong>Systematic Component</strong></p>
<p><span class="math display">\[
\theta_i = g(X_i, \beta)
\]</span></p>
<p>In words, the above is saying something like:</p>
<ul>
<li>The predicted response <span class="math inline">\(Y_i\)</span> for a set of predictors <span class="math inline">\(X_i\)</span> is assumed to be drawn from (the <span class="math inline">\(\sim\)</span> symbol) a stochastic distribution (<span class="math inline">\(f(.,.)\)</span>)</li>
<li>The stochastic distribution contains both parameters we’re interested in, and which are determined by the data <span class="math inline">\(\theta_i\)</span>, and parameters we’re not interested in and might just have to assume, <span class="math inline">\(\alpha\)</span>.</li>
<li>The parameters we’re interested in determining from the data <span class="math inline">\(\theta_i\)</span> are themselves determined by a systematic component <span class="math inline">\(g(.,.)\)</span> which take and transform two inputs: The observed predictor data <span class="math inline">\(X_i\)</span>, and a set of coefficients <span class="math inline">\(\beta\)</span></li>
</ul>
<p>And graphically this looks something like:</p>
<div class="cell">
<div class="cell-output-display">
<div>
<div>
<pre class="mermaid mermaid-js">flowchart LR
  X
  beta
  g
  f
  alpha
  theta
  Y
  
  X --&gt; g
  beta --&gt; g
  g --&gt; theta
  theta --&gt; f
  alpha --&gt; f
  
  f --&gt; Y

</pre>
</div>
</div>
</div>
</div>
<p>To understand how this fits into the ‘whole game’ of modelling, it’s worth introducing another term, <span class="math inline">\(D\)</span>, for the data we’re using, and to say that <span class="math inline">\(D\)</span> is partitioned into observed predictors <span class="math inline">\(X_i\)</span>, and observed responses, <span class="math inline">\(y_i\)</span>.</p>
<p>For each observation, <span class="math inline">\(i\)</span>, we therefore have a predicted response, <span class="math inline">\(Y_i\)</span>, and an observed response, <span class="math inline">\(y_i\)</span>. We can compare <span class="math inline">\(Y_i\)</span> with <span class="math inline">\(y_i\)</span> to get the difference between the two, <span class="math inline">\(\delta_i\)</span>.</p>
<p>Now, obviously can’t change the data to make it fit our model better. But what we can do is calibrate the model a little better. How do we do this? Through adjusting the <span class="math inline">\(\beta\)</span> parameters that feed into the systematic component <span class="math inline">\(g\)</span>. Graphically, this process of comparison, adjustment, and calibration looks as follows:</p>
<div class="cell">
<div class="cell-output-display">
<div>
<div>
<pre class="mermaid mermaid-js">flowchart LR
  D
  y
  X
  beta
  g
  f
  alpha
  theta
  Y
  diff
  
  D --&gt;|partition| X
  D --&gt;|partition| y
  X --&gt; g
  beta --&gt;|rerun| g
  g --&gt;|transform| theta
  theta --&gt; f
  alpha --&gt; f
  
  f --&gt;|predict| Y
  
  Y --&gt;|compare| diff
  y --&gt;|compare| diff
  
  diff --&gt;|adjust| beta
  
  
  
  linkStyle default stroke:blue, stroke-width:1px

</pre>
</div>
</div>
</div>
</div>
<p>Pretty much all statistical model fitting involves iterating along this <span class="math inline">\(g \to \beta\)</span> and <span class="math inline">\(\beta \to g\)</span> feedback loop until some kind of condition is met involving minimising <span class="math inline">\(\delta\)</span>.</p>
</section>
<section id="systematic-components-and-link-functions" class="level2">
<h2 class="anchored" data-anchor-id="systematic-components-and-link-functions">Systematic components and link functions</h2>
<p>The two part equation shown above is too general and abstract to be implemented directly. Instead, specific choices about the <span class="math inline">\(f(.)\)</span> and <span class="math inline">\(g(.)\)</span> need to be made. <span class="citation" data-cites="KinTomWit00">King, Tomz, and Wittenberg (<a href="#ref-KinTomWit00" role="doc-biblioref">2000</a>)</span> gives the following examples:</p>
<p><strong>Logistic Regression</strong></p>
<p><span class="math display">\[
Y_i \sim Bernoulli(\pi_i)
\]</span></p>
<p><span class="math display">\[
\pi_i = \frac{1}{1 + e^{-X_i\beta}}
\]</span></p>
<p><strong>Linear Regression</strong></p>
<p><span class="math display">\[
Y_i \sim N(\mu_i, \sigma^2)
\]</span> <span class="math display">\[
\mu_i = X_i\beta
\]</span></p>
<p>So, what’s so special about linear regression, in this framework?</p>
<p>In one sense, not so much. It’s got a systematic component, and it’s got a stochastic component. But so do other models. But in another sense, quite a lot. It’s a rare case where the systematic component, <span class="math inline">\(g(.)\)</span>, <em>doesn’t</em> transform its inputs in some weird and wonderful way. We can say that <span class="math inline">\(g(.)\)</span> is the identity transform, <span class="math inline">\(I(.)\)</span>, which in words means <em>take what you’re given, do nothing to it, and pass it on</em>.</p>
<p>By contrast, the systematic component for logistic regression is known as the logistic function. <span class="math inline">\(logistic(x) := \frac{1}{1 + e^{-x}}\)</span> It transforms inputs that could be anywhere on the real number line to values that lay somewhere between 0 and 1. Why 0 to 1? Because what logistic regression models produce aren’t predicted values, but predicted <em>probabilities</em>, and nothing can be more probable than certain (1) or less probable than impossible (0).</p>
<p>We can compare the transformations used in linear and logistic regression as follows:<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a></p>
<div>
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Define transformations</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>ident <span class="ot">&lt;-</span> <span class="cf">function</span>(x) {x}</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>lgt <span class="ot">&lt;-</span> <span class="cf">function</span>(x) {<span class="dv">1</span> <span class="sc">/</span> (<span class="dv">1</span> <span class="sc">+</span> <span class="fu">exp</span>(<span class="sc">-</span>x))}</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Draw the associations</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">curve</span>(ident, <span class="sc">-</span><span class="dv">6</span>, <span class="dv">6</span>,</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>      <span class="at">xlab =</span> <span class="st">"x (before transform)"</span>,</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>      <span class="at">ylab =</span> <span class="st">"z (after transform)"</span>,</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>      <span class="at">main =</span> <span class="st">"The Identity 'Transformation'"</span></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>      )</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="fu">curve</span>(lgt, <span class="sc">-</span><span class="dv">6</span>, <span class="dv">6</span>, </span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>      <span class="at">xlab =</span> <span class="st">"x (before transform)"</span>, </span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>      <span class="at">ylab =</span> <span class="st">"z (after transform)"</span>,</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>      <span class="at">main =</span> <span class="st">"The Logistic Transformation"</span></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>      )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell quarto-layout-panel">
<div class="quarto-layout-row quarto-layout-valign-top">
<div class="cell-output-display quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Identity Transformation</figcaption>
</figure>
</div>
</div>
<div class="cell-output-display quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-3-2.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Logistic Transformation</figcaption>
</figure>
</div>
</div>
</div>
</div>
</div>
<p>The usual input to the transformation function <span class="math inline">\(g(.)\)</span> is a sum of products. For three variables, for example, this could be <span class="math inline">\(\beta_0 + \beta_1 x_1 + \beta_2 x_2\)</span>. In matrix algebra this generalises to <span class="math inline">\(\boldsymbol{X\beta}\)</span> , where <span class="math inline">\(\boldsymbol{X}\)</span> is the predictor data whose rows are observations, columns are variables, and whose first column is a vector of 1s (for the intercept term). The <span class="math inline">\(\boldsymbol{\beta}\)</span> term is a row-wise vector comprising each specific <span class="math inline">\(\beta\)</span> term, such as <span class="math inline">\(\boldsymbol{\beta} = \{ \beta_0, \beta_1, \beta_2 \}\)</span> in the three variable example above.</p>
<p>What’s special about the identity transformation, and so linear regression, is that there is a fairly clear correspondence between a <span class="math inline">\(\beta_j\)</span> term and the estimated influence of changing a predictor variable <span class="math inline">\(x_j\)</span> on the predicted outcome <span class="math inline">\(Y\)</span>, i.e.&nbsp;the ‘effect of <span class="math inline">\(x_j\)</span> on <span class="math inline">\(Y\)</span>’. For other transformations this tends to not be the case.</p>
</section>
<section id="how-to-express-a-linear-model-as-a-generalised-linear-model" class="level2">
<h2 class="anchored" data-anchor-id="how-to-express-a-linear-model-as-a-generalised-linear-model">How to express a linear model as a generalised linear model</h2>
<p>In R, there’s the <code>lm</code> function for linear models, and the <code>glm</code> function for generalised linear models.</p>
<p>I’ve argued previously that the standard linear regression is just a specific type of generalised linear model, one that makes use of an identity transformation <code>I(.)</code> for its systematic component <code>g(.)</code>. Let’s now demonstrate that by producing the same model specification using both <code>lm</code> and <code>glm</code>.</p>
<p>We can start by being painfully unimaginative and picking using one of R’s standard datasets</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>iris <span class="sc">|&gt;</span> </span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(Petal.Length, Sepal.Length)) <span class="sc">+</span> </span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span> </span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"The Iris dataset *Yawn*"</span>,</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Petal Length"</span>,</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Sepal Length"</span></span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span> </span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">expand_limits</span>(<span class="at">x =</span> <span class="dv">0</span>, <span class="at">y =</span> <span class="dv">0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>It looks like, where the petal length is over 2.5, the relationship with sepal length is fairly linear</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>iris <span class="sc">|&gt;</span> </span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Petal.Length <span class="sc">&gt;</span> <span class="fl">2.5</span>) <span class="sc">|&gt;</span> </span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(Petal.Length, Sepal.Length)) <span class="sc">+</span> </span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span> </span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"The Iris dataset *Yawn*"</span>,</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Petal Length"</span>,</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Sepal Length"</span></span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span> </span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">expand_limits</span>(<span class="at">x =</span> <span class="dv">0</span>, <span class="at">y =</span> <span class="dv">0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>So, let’s make a linear regression just of this subset</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>iris_ss <span class="ot">&lt;-</span> </span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>  iris <span class="sc">|&gt;</span> </span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Petal.Length <span class="sc">&gt;</span> <span class="fl">2.5</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>We can produce the regression using <code>lm</code> as follows:</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>mod_lm <span class="ot">&lt;-</span> <span class="fu">lm</span>(Sepal.Length <span class="sc">~</span> Petal.Length, <span class="at">data =</span> iris_ss)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>And we can use the <code>summary</code> function (which checks the type of <code>mod_lm</code> and evokes <code>summary.lm</code> implicitly) to get the following:</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod_lm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Sepal.Length ~ Petal.Length, data = iris_ss)

Residuals:
     Min       1Q   Median       3Q      Max 
-1.09194 -0.26570  0.00761  0.21902  0.87502 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   2.99871    0.22593   13.27   &lt;2e-16 ***
Petal.Length  0.66516    0.04542   14.64   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.3731 on 98 degrees of freedom
Multiple R-squared:  0.6864,    Adjusted R-squared:  0.6832 
F-statistic: 214.5 on 1 and 98 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Woohoo! Three stars next to the <code>Petal.Length</code> coefficient! Definitely publishable!</p>
<p>To do the same using <code>glm</code>.</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>mod_glm <span class="ot">&lt;-</span> <span class="fu">glm</span>(Sepal.Length <span class="sc">~</span> Petal.Length, <span class="at">data =</span> iris_ss)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>And we can use the <code>summary</code> function for this data too. In this case, <code>summary</code> evokes <code>summary.glm</code> because it knows the class of <code>mod_glm</code> contains <code>glm</code>.</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod_glm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = Sepal.Length ~ Petal.Length, data = iris_ss)

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   2.99871    0.22593   13.27   &lt;2e-16 ***
Petal.Length  0.66516    0.04542   14.64   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for gaussian family taken to be 0.1391962)

    Null deviance: 43.496  on 99  degrees of freedom
Residual deviance: 13.641  on 98  degrees of freedom
AIC: 90.58

Number of Fisher Scoring iterations: 2</code></pre>
</div>
</div>
<p>So, the coefficients are exactly the same. But there’s also some additional information in the summary, including on the type of ‘family’ used. Why is this?</p>
<p>If we look at the help for <code>glm</code> we can see that, by default, the <code>family</code> argument is set to <code>gaussian</code>.</p>
<p>And if we delve a bit further into the help file, in the details about the family argument, it links to the <code>family</code> help page. The usage statement of the <code>family</code> help file is as follows:</p>
<pre><code>family(object, ...)

binomial(link = "logit")
gaussian(link = "identity")
Gamma(link = "inverse")
inverse.gaussian(link = "1/mu^2")
poisson(link = "log")
quasi(link = "identity", variance = "constant")
quasibinomial(link = "logit")
quasipoisson(link = "log")</code></pre>
<p>Each family has a default <code>link</code> argument, and for this <code>gaussian</code> family, this link is the identity function.</p>
<p>We can also see that, for both the <code>binomial</code> and <code>quasibinomial</code> family, the default link is <code>logit</code>, which transforms all predictors onto a 0-1 scale, as shown in the last post.</p>
<p>So, by using the default family, the Gaussian family is selected, and by using the default Gaussian family member, the identity link is selected.</p>
<p>We can confirm this by setting the family and link explicitly, showing that we get the same results</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>mod_glm2 <span class="ot">&lt;-</span> <span class="fu">glm</span>(Sepal.Length <span class="sc">~</span> Petal.Length, <span class="at">family =</span> <span class="fu">gaussian</span>(<span class="at">link =</span> <span class="st">"identity"</span>), <span class="at">data =</span> iris_ss)</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod_glm2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = Sepal.Length ~ Petal.Length, family = gaussian(link = "identity"), 
    data = iris_ss)

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   2.99871    0.22593   13.27   &lt;2e-16 ***
Petal.Length  0.66516    0.04542   14.64   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for gaussian family taken to be 0.1391962)

    Null deviance: 43.496  on 99  degrees of freedom
Residual deviance: 13.641  on 98  degrees of freedom
AIC: 90.58

Number of Fisher Scoring iterations: 2</code></pre>
</div>
</div>
<p>It’s the same!</p>
<p>How do these terms used in the <code>glm</code> function, <code>family</code> and <code>link</code>, relate to the general framework in <span class="citation" data-cites="KinTomWit00">King, Tomz, and Wittenberg (<a href="#ref-KinTomWit00" role="doc-biblioref">2000</a>)</span>?</p>
<ul>
<li><code>family</code> is the stochastic component, <code>f(.)</code></li>
<li><code>link</code> is the systematic component, <code>g(.)</code></li>
</ul>
<p>They’re different terms, but it’s the same broad framework.</p>
<p>Linear models are just one type of general linear model!</p>
</section>
<section id="why-only-betas-look-at-betas" class="level2">
<h2 class="anchored" data-anchor-id="why-only-betas-look-at-betas">Why only betas look at betas</h2>
<section id="why-overuse-of-linear-regression-leads-people-to-look-at-models-in-the-wrong-way" class="level3">
<h3 class="anchored" data-anchor-id="why-overuse-of-linear-regression-leads-people-to-look-at-models-in-the-wrong-way">Why overuse of linear regression leads people to look at models in the wrong way</h3>
<p>Though it’s not always phrased this way, a motivating question behind the construction of most statistical models is, “What influence does a single input to the model, <span class="math inline">\(x_j\)</span>, have on the output, <span class="math inline">\(Y\)</span>?”<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a> For a single variable <span class="math inline">\(x_j\)</span> which is either present (<code>1</code>) or absent (<code>0</code>), this is in effect asking what is <span class="math inline">\(E(Y | x_j = 1) - E(Y | x_j = 0)\)</span> ?<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a></p>
<p>Let’s look at a linear regression case, then a logistic regression case.</p>
</section>
<section id="linear-regression-example" class="level3">
<h3 class="anchored" data-anchor-id="linear-regression-example">Linear Regression example</h3>
<p>Using the iris dataset, let’s try to predict Sepal Width (a continuous variable) on Sepal Length (a continuous variable) and whether the species is setosa or not (a discrete variable). As a reminder, the data relating these three variables look as follows:</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>iris <span class="sc">|&gt;</span></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ggplot</span>(<span class="fu">aes</span>(Sepal.Length, Sepal.Width, <span class="at">group =</span> Species, <span class="at">colour =</span> Species, <span class="at">shape =</span> Species)) <span class="sc">+</span> </span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_point</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Let’s now build the model:</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> iris <span class="sc">|&gt;</span> <span class="fu">mutate</span>(<span class="at">is_setosa =</span> Species <span class="sc">==</span> <span class="st">'setosa'</span>)</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>mod_lm <span class="ot">&lt;-</span> <span class="fu">lm</span>(Sepal.Width <span class="sc">~</span> Sepal.Length <span class="sc">+</span> is_setosa, <span class="at">data =</span> df)</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>mod_lm</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Sepal.Width ~ Sepal.Length + is_setosa, data = df)

Coefficients:
  (Intercept)   Sepal.Length  is_setosaTRUE  
       0.7307         0.3420         0.9855  </code></pre>
</div>
</div>
<p>The coefficients <span class="math inline">\(\boldsymbol{\beta} = \{\beta_0, \beta_1, \beta_2\}\)</span> are <span class="math inline">\(\{0.73, 0.34, 0.99\}\)</span>, and refer to the intercept, Sepal Length and <code>is_setosa</code> respectively.</p>
<p>If we assume a Sepel Length of 6, for example, then the expected Sepal Width (the thing we are predicting) is <code>0.73 + 6 * 0.34 + 0.99</code> or about <code>3.77</code> in the case where <code>is_setosa</code> is true, and <code>0.73 + 6 * 0.34</code> or about <code>2.78</code> where <code>is_setosa</code> is false.</p>
<p>The difference between these two values, <code>3.77</code> and <code>2.78</code>, i.e.&nbsp;the ‘influence of setosa’ on the outcome, is <code>0.99</code>, i.e.&nbsp;the <span class="math inline">\(\beta_2\)</span> coefficient shown before. In fact, for any conceivable (and non-conceivable, i.e.&nbsp;negative) value of Sepal Length, the difference is still <code>0.99</code>.</p>
<p>This is the <span class="math inline">\(\beta_2\)</span> coefficient, and the reason why, <strong>for linear regression, and almost exclusively linear regression, looking at the coefficients themselves provides substantively meaningful information</strong> (something <span class="citation" data-cites="KinTomWit00">King, Tomz, and Wittenberg (<a href="#ref-KinTomWit00" role="doc-biblioref">2000</a>)</span> calls a ‘quantity of interest’) about the size of influence that a predictor has on a response.</p>
</section>
<section id="logistic-regression-example" class="level3">
<h3 class="anchored" data-anchor-id="logistic-regression-example">Logistic Regression example</h3>
<p>Now let’s look at an example using logistic regression. We will use another tiresomely familiar dataset, <code>mtcars</code>. We are interested in estimating the effect that having a straight engine (<code>vs=1</code>) has on the probability of the car having a manual transmission (<code>am=1</code>). Our model also tries to control for the miles-per-gallon (<code>mpg</code>). The model specification is shown, the model is run, and the coefficeints are all shown below:</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>mod_logistic <span class="ot">&lt;-</span> <span class="fu">glm</span>(</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>    am <span class="sc">~</span> mpg <span class="sc">+</span> vs,</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">data =</span> mtcars, </span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">family =</span> <span class="fu">binomial</span>()</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>mod_logistic</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:  glm(formula = am ~ mpg + vs, family = binomial(), data = mtcars)

Coefficients:
(Intercept)          mpg           vs  
    -9.9183       0.5359      -2.7957  

Degrees of Freedom: 31 Total (i.e. Null);  29 Residual
Null Deviance:      43.23 
Residual Deviance: 24.94    AIC: 30.94</code></pre>
</div>
</div>
<p>Here the coefficients <span class="math inline">\(\boldsymbol{\beta} = \{\beta_0, \beta_1, \beta_2\}\)</span> are <span class="math inline">\(\{-9.92, 0.54, -2.80\}\)</span>, and refer to the intercept, mpg, and vs respectively.</p>
<p>But what does this actually mean, substantively?</p>
</section>
<section id="dont-stargaze" class="level3">
<h3 class="anchored" data-anchor-id="dont-stargaze">(Don’t) Stargaze</h3>
<p>A very common approach to trying to answer this question is to look at the statistical significance of the coefficients, which we can do with the <code>summary()</code> function</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod_logistic)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = am ~ mpg + vs, family = binomial(), data = mtcars)

Coefficients:
            Estimate Std. Error z value Pr(&gt;|z|)   
(Intercept)  -9.9183     3.4942  -2.839  0.00453 **
mpg           0.5359     0.1967   2.724  0.00644 **
vs           -2.7957     1.4723  -1.899  0.05758 . 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 43.230  on 31  degrees of freedom
Residual deviance: 24.944  on 29  degrees of freedom
AIC: 30.944

Number of Fisher Scoring iterations: 6</code></pre>
</div>
</div>
<p>A common practice in many social and health sciences is to offer something like a narrative summary of the above, something like:</p>
<blockquote class="blockquote">
<p>Our logistic regression model indicates that manualness is positively and significantly associated with our measure of fuel efficiency (p &lt; 0.01). There is also an indication of a negative association with straight engine, but this effect does not quite meet conventional thresholds for statistical significance (p &lt; 0.10).</p>
</blockquote>
<p>This above practice is known as ‘star-gazing’, because summary tables like those above tend to have one or more <code>*</code> symbols in the final row, if the value of the <code>Pr(&gt;|z|)</code> is below 0.05, and narrative summaries like those just above tend to involve looking at the number of stars in each row, alongside whether the <code>Estimate</code> values have a minus sign in front of them.</p>
<p>Star gazing is a very common practice. It’s also a terrible practice, which - ironically - turns the final presented output of a <em>quantitative</em> model into the crudest of <em>qualitative</em> summaries (positive, negative; significant, not significant). Star gazing is what researchers tend to default to when presented with model outputs from the above because, unlike in the linear regression example, the extent to which the <span class="math inline">\(\beta\)</span> coefficients answer substantive ‘how-much’-ness questions, like “How much does having a straight engine change the probability of manual transmission?, is not easily apparent from the coefficients themselves.</p>
</section>
<section id="standardisation" class="level3">
<h3 class="anchored" data-anchor-id="standardisation">Standardisation</h3>
<p>So, how can we do better?</p>
<p>One approach is to standardise the data that goes into the model before passing them to the model. Standardisation means attempting to make the distribution and range of different variables more similar, and is especially useful when comparing between different continuous variables.</p>
<p>To give an example of this, let’s look at a specification with weight (<code>wt</code>) and horsepower (<code>hp</code>) in place of <code>mpg</code>, but keeping engine-type indicator (<code>vs</code>):</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>mod_logistic_2 <span class="ot">&lt;-</span> <span class="fu">glm</span>(</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>    am <span class="sc">~</span> vs <span class="sc">+</span> wt <span class="sc">+</span> hp,</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">data =</span> mtcars, </span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">family =</span> <span class="fu">binomial</span>()</span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod_logistic_2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = am ~ vs + wt + hp, family = binomial(), data = mtcars)

Coefficients:
            Estimate Std. Error z value Pr(&gt;|z|)  
(Intercept) 25.35510   11.24613   2.255   0.0242 *
vs          -3.12906    2.92958  -1.068   0.2855  
wt          -9.64982    4.05528  -2.380   0.0173 *
hp           0.03242    0.01959   1.655   0.0979 .
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 43.2297  on 31  degrees of freedom
Residual deviance:  8.5012  on 28  degrees of freedom
AIC: 16.501

Number of Fisher Scoring iterations: 8</code></pre>
</div>
</div>
<p>Here both <code>wt</code> and <code>hp</code> are continuous variables.</p>
<p>A star gazing zombie might say something like</p>
<blockquote class="blockquote">
<p>manualness is negatively and significantly associated with weight (p &lt; 0.05); there is a positive association with horsepower but this does not meet standard thresholds of statistical significance (0.05 &lt; p &lt; 0.10).</p>
</blockquote>
<p>A <em>slightly</em> better approach would be to standardise the variables <code>wt</code> and <code>hp</code> before passing to the model. Standardising means trying to set the variables to a common scale, and giving the variables more similar statistical characteristics.</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>standardise <span class="ot">&lt;-</span> <span class="cf">function</span>(x){</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>  (x <span class="sc">-</span> <span class="fu">mean</span>(x)) <span class="sc">/</span> <span class="fu">sd</span>(x)</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>mtcars_z <span class="ot">&lt;-</span> mtcars</span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>mtcars_z<span class="sc">$</span>wt_z <span class="ot">=</span> <span class="fu">standardise</span>(mtcars<span class="sc">$</span>wt)</span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a>mtcars_z<span class="sc">$</span>hp_z <span class="ot">=</span> <span class="fu">standardise</span>(mtcars<span class="sc">$</span>hp)</span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-9"><a href="#cb23-9" aria-hidden="true" tabindex="-1"></a>mod_logistic_2_z <span class="ot">&lt;-</span> <span class="fu">glm</span>(</span>
<span id="cb23-10"><a href="#cb23-10" aria-hidden="true" tabindex="-1"></a>    am <span class="sc">~</span> vs <span class="sc">+</span> wt_z <span class="sc">+</span> hp_z,</span>
<span id="cb23-11"><a href="#cb23-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">data =</span> mtcars_z, </span>
<span id="cb23-12"><a href="#cb23-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">family =</span> <span class="fu">binomial</span>()</span>
<span id="cb23-13"><a href="#cb23-13" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb23-14"><a href="#cb23-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-15"><a href="#cb23-15" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod_logistic_2_z)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = am ~ vs + wt_z + hp_z, family = binomial(), data = mtcars_z)

Coefficients:
            Estimate Std. Error z value Pr(&gt;|z|)  
(Intercept)  -0.9348     1.4500  -0.645   0.5191  
vs           -3.1291     2.9296  -1.068   0.2855  
wt_z         -9.4419     3.9679  -2.380   0.0173 *
hp_z          2.2230     1.3431   1.655   0.0979 .
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 43.2297  on 31  degrees of freedom
Residual deviance:  8.5012  on 28  degrees of freedom
AIC: 16.501

Number of Fisher Scoring iterations: 8</code></pre>
</div>
</div>
<p><code>wt_z</code> is the standardised version of <code>wt</code>, and <code>hp_z</code> is the standardised version of <code>hp</code>. By convention, whereas unstandardised coefficients are usually referred to as <span class="math inline">\(\beta\)</span> (‘beta’) coefficients, standardised coefficients are instead referred to as <span class="math inline">\(b\)</span> coefficients. But really, it’s the same model.</p>
<p>Note the p value of <code>wt_z</code> is the same as for <code>wt</code>, and the p value of <code>hp_z</code> is the same as that for <code>hp</code>. Note also the directions of effect are the same: the coefficients on <code>wt</code> and <code>wt_z</code> are both negative, and the coefficients of <code>hp</code> and <code>hp_z</code> are both positive.</p>
<p>This isn’t a coincidence. Of course standardising can’t really add any new information, can’t really change the relationship between a predictor and a response. It’s not <em>really</em> a new variable, it’s the same old variable, so the relationship between predictor and response that there used to be is still there now.</p>
<p>So why bother standardising?</p>
<p>One reason is it gives, subject to some assumptions and caveats, a way of gauging the relative importance of the two different continuous variables, by allowing a slightly more meaningful comparison between the two coefficients.</p>
<p>In this case, we have a standardised <span class="math inline">\(b\)</span> coefficient of <code>-9.44</code> for <code>wt_z</code>, and of <code>2.22</code> for <code>hp_z</code>. As with the unstandardised coefficients we can still assert that manualness is negatively associated with weight, and positively associated with horsepower. But now we can also compare the two numbers <code>-9.44</code> and <code>2.22</code>. The ratio of these two numbers is around <code>4.3</code>. So, we might hazard to suggest something like:</p>
<blockquote class="blockquote">
<p>a given increase in weight is around four times as important in <em>negatively predicting</em> manual transmission (i.e.&nbsp;in predicting an automatic transmission) as an equivalent increase in horsepower is in <em>positively predicting</em> manual transmission.</p>
</blockquote>
<p>This isn’t a statement that’s easy to parse, but does at least allow slightly more information to be gleamed from the model. For example, it implies that, if a proposed change to a vehicle leads to similar relative (standardised) increases in both weight and horsepower then, as the weight effect is greater than the horsepower effect, the model will predict a <em>decreased</em> probability of manualness as a result.</p>
<p>But what about the motivating question, “What’s <em>the</em> effect of a straight engine (<code>vs=1</code>) on the probability of manual transmission (<code>am=1</code>)?”</p>
<p>The problem, unlike with the linear regression, is this is now a badly formulated question, based on an incorrect premise. The problem is with the word ‘the’, which implies there should be a single answer to this question, i.e.&nbsp;that the effect of <code>vs</code> on the probability of <code>am=1</code> should always be the same. But, at least when it comes to absolute changes in the probability of <code>am=1</code>, this is no longer the case, as it depends on the values of the other variables in the model.</p>
<p>Instead of assuming <code>vs=1</code> has a single effect on <code>P(am=1)</code>, we instead need to think about predictions of the marginal effects of <code>vs</code> on <code>am</code> in the context of other plausible values of the other predictors in the model, <code>wt</code> and <code>hp</code>. This involves asking the model a series of well formulated and specific questions.</p>
</section>
<section id="maximum-marginal-effects-divide-by-four" class="level3">
<h3 class="anchored" data-anchor-id="maximum-marginal-effects-divide-by-four">Maximum marginal effects: Divide-by-four</h3>
<p>Before we do that, however, there’s a useful heuristic that can be employed when looking at discrete variables and using a logistic regression specification. The heuristic, which is based on the properties of the logistic function,<a href="#fn4" class="footnote-ref" id="fnref4" role="doc-noteref"><sup>4</sup></a> is called <em>divide-by-four</em>. What this means is that, if we take the coefficient on <code>vs</code> of <code>-3.13</code>, and divide this value by four, we get a value of <code>-0.78</code>. Notice that the absolute value of <code>-0.78</code> is between 0 and 1.<a href="#fn5" class="footnote-ref" id="fnref5" role="doc-noteref"><sup>5</sup></a> What this value gives is the <em>maximum possible</em> effect that the discrete variable (the presence rather than absence of a straight engine) has on the probability of being a manual transmission. We can say, “a straight engine <em>reduces</em> the probability of a manual transmission by <em>up to</em> 78%”</p>
<p>But, as mentioned, this doesn’t quite answer the motivating question, it gives an upper bound to the answer, not the answer itself.<a href="#fn6" class="footnote-ref" id="fnref6" role="doc-noteref"><sup>6</sup></a> We can instead start to get a sense of ‘the’ effect of the variable <code>vs</code> on <code>P(am=1)</code> by asking the model a series of questions.</p>
</section>
<section id="predictions-on-a-matrix" class="level3">
<h3 class="anchored" data-anchor-id="predictions-on-a-matrix">Predictions on a matrix</h3>
<p>We can start by getting the range of observed values for the two continuous variables, <code>hp</code> and <code>mpg</code>:</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">min</span>(mtcars<span class="sc">$</span>hp)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 52</code></pre>
</div>
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">max</span>(mtcars<span class="sc">$</span>hp)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 335</code></pre>
</div>
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">min</span>(mtcars<span class="sc">$</span>wt)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.513</code></pre>
</div>
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">max</span>(mtcars<span class="sc">$</span>wt)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 5.424</code></pre>
</div>
</div>
<p>We can then ask the model to make predictions of <span class="math inline">\(P(am=1)\)</span> for a large number of values of <code>hp</code> and <code>wt</code> within the observed range, both in the condition in which <code>vs=0</code> and in the condition in which <code>vs=1</code>. The <code>expand_grid</code> function<a href="#fn7" class="footnote-ref" id="fnref7" role="doc-noteref"><sup>7</sup></a> can help us do this:</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>predictors <span class="ot">&lt;-</span> <span class="fu">expand_grid</span>(</span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">hp =</span> <span class="fu">seq</span>(<span class="fu">min</span>(mtcars<span class="sc">$</span>hp), <span class="fu">max</span>(mtcars<span class="sc">$</span>hp), <span class="at">length.out =</span> <span class="dv">100</span>),</span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">wt =</span> <span class="fu">seq</span>(<span class="fu">min</span>(mtcars<span class="sc">$</span>wt), <span class="fu">max</span>(mtcars<span class="sc">$</span>wt), <span class="at">length.out =</span> <span class="dv">100</span>)</span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a>predictors_straight <span class="ot">&lt;-</span> predictors <span class="sc">|&gt;</span> </span>
<span id="cb33-7"><a href="#cb33-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">vs =</span> <span class="dv">1</span>)</span>
<span id="cb33-8"><a href="#cb33-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-9"><a href="#cb33-9" aria-hidden="true" tabindex="-1"></a>predictors_vshaped <span class="ot">&lt;-</span> predictors <span class="sc">|&gt;</span> </span>
<span id="cb33-10"><a href="#cb33-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">vs =</span> <span class="dv">0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>For each of these permutations of inputs, we can use the model to get a conditional prediction. For convenience, we can also attach this as an additional column to the predictor data frame:</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>predictions_predictors_straight <span class="ot">&lt;-</span> predictors_straight <span class="sc">|&gt;</span> </span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">p_manual =</span> <span class="fu">predict</span>(mod_logistic_2, <span class="at">type =</span> <span class="st">"response"</span>, <span class="at">newdata =</span> predictors_straight)</span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a>predictions_predictors_vshaped <span class="ot">&lt;-</span> predictors_vshaped <span class="sc">|&gt;</span> </span>
<span id="cb34-7"><a href="#cb34-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb34-8"><a href="#cb34-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">p_manual =</span> <span class="fu">predict</span>(mod_logistic_2, <span class="at">type =</span> <span class="st">"response"</span>, <span class="at">newdata =</span> predictors_vshaped)</span>
<span id="cb34-9"><a href="#cb34-9" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>We can see how the predictions vary over <code>hp</code> and <code>wt</code> using a heat map or contour map:</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>predictions_predictors_straight <span class="sc">|&gt;</span> </span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">bind_rows</span>(</span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>    predictions_predictors_vshaped</span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span> </span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> hp, <span class="at">y =</span> wt, <span class="at">z =</span> p_manual)) <span class="sc">+</span> </span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_contour_filled</span>() <span class="sc">+</span> </span>
<span id="cb35-7"><a href="#cb35-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>vs) <span class="sc">+</span></span>
<span id="cb35-8"><a href="#cb35-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb35-9"><a href="#cb35-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Predicted probability of manual transmission by wt, hp, and vs"</span></span>
<span id="cb35-10"><a href="#cb35-10" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>We can also produce a contour map of the differences between these two contour maps, i.e.&nbsp;the effect of a straight (<code>vs=1</code>) compared with v-shaped (<code>vs=0</code>) engine, which gets us a bit closer to the answer:</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>predictions_predictors_straight <span class="sc">|&gt;</span> </span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">bind_rows</span>(</span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>    predictions_predictors_vshaped</span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span> </span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(hp, wt) <span class="sc">|&gt;</span> </span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb36-7"><a href="#cb36-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">diff_p_manual =</span> p_manual[vs<span class="sc">==</span><span class="dv">1</span>] <span class="sc">-</span> p_manual[vs<span class="sc">==</span><span class="dv">0</span>]</span>
<span id="cb36-8"><a href="#cb36-8" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span> </span>
<span id="cb36-9"><a href="#cb36-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>() <span class="sc">|&gt;</span> </span>
<span id="cb36-10"><a href="#cb36-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(</span>
<span id="cb36-11"><a href="#cb36-11" aria-hidden="true" tabindex="-1"></a>    <span class="fu">aes</span>(<span class="at">x =</span> hp, <span class="at">y =</span> wt, <span class="at">z =</span> diff_p_manual)</span>
<span id="cb36-12"><a href="#cb36-12" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span> </span>
<span id="cb36-13"><a href="#cb36-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_contour_filled</span>() <span class="sc">+</span> </span>
<span id="cb36-14"><a href="#cb36-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb36-15"><a href="#cb36-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Marginal effect of vs=1 given wt and hp on P(am=1)"</span></span>
<span id="cb36-16"><a href="#cb36-16" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-22-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>We can see here that, for large ranges of wt and hp, the marginal effect of <code>vs=1</code> is small. However, for particular combinations of hp and wt, such as where hp is around 200 and wt is slightly below 3, then the marginal effect of <code>vs=1</code> becomes large, up to around a -70% reduction in the probability of manual transmission. (i.e.&nbsp;similar to the theoretical maximum marginal effect of around -78%).</p>
<p>So, what’s <em>the</em> effect of <code>vs=1</code> on <code>P(am=1)</code>? i.e.&nbsp;how should we boil down all these 10,000 predicted effect sizes into a single effect size?</p>
<p>I guess, if we have to try to answer this silly question, then we could take the average effect size…</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>predictions_predictors_straight <span class="sc">|&gt;</span> </span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">bind_rows</span>(</span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>    predictions_predictors_vshaped</span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span> </span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(hp, wt) <span class="sc">|&gt;</span> </span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb37-7"><a href="#cb37-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">diff_p_manual =</span> p_manual[vs<span class="sc">==</span><span class="dv">1</span>] <span class="sc">-</span> p_manual[vs<span class="sc">==</span><span class="dv">0</span>]</span>
<span id="cb37-8"><a href="#cb37-8" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span> </span>
<span id="cb37-9"><a href="#cb37-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>() <span class="sc">|&gt;</span> </span>
<span id="cb37-10"><a href="#cb37-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb37-11"><a href="#cb37-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">mean_diff_p_manual =</span> <span class="fu">mean</span>(diff_p_manual)</span>
<span id="cb37-12"><a href="#cb37-12" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 1
  mean_diff_p_manual
               &lt;dbl&gt;
1            -0.0821</code></pre>
</div>
</div>
<p>So, we get an average difference of around <code>-0.08</code>, i.e.&nbsp;about an 8% reduction in probability of manual transmission.</p>
</section>
<section id="marginal-effects-on-observed-data" class="level3">
<h3 class="anchored" data-anchor-id="marginal-effects-on-observed-data">Marginal effects on observed data</h3>
<p>Is this a reasonable answer? Probably not, because although the permutations of <code>wt</code> and <code>hp</code> we looked at come from the observed range, most of these combinations are likely very ‘theoretical’. We can get a sense of this by plotting the observed values of <code>wt</code> and <code>hp</code> onto the above contour map:</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>predictions_predictors_straight <span class="sc">|&gt;</span> </span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">bind_rows</span>(</span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>    predictions_predictors_vshaped</span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span> </span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(hp, wt) <span class="sc">|&gt;</span> </span>
<span id="cb39-6"><a href="#cb39-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb39-7"><a href="#cb39-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">diff_p_manual =</span> p_manual[vs<span class="sc">==</span><span class="dv">1</span>] <span class="sc">-</span> p_manual[vs<span class="sc">==</span><span class="dv">0</span>]</span>
<span id="cb39-8"><a href="#cb39-8" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span> </span>
<span id="cb39-9"><a href="#cb39-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>() <span class="sc">|&gt;</span> </span>
<span id="cb39-10"><a href="#cb39-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(</span>
<span id="cb39-11"><a href="#cb39-11" aria-hidden="true" tabindex="-1"></a>    <span class="fu">aes</span>(<span class="at">x =</span> hp, <span class="at">y =</span> wt, <span class="at">z =</span> diff_p_manual)</span>
<span id="cb39-12"><a href="#cb39-12" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span> </span>
<span id="cb39-13"><a href="#cb39-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_contour_filled</span>(<span class="at">alpha =</span> <span class="fl">0.2</span>, <span class="at">show.legend =</span> <span class="cn">FALSE</span>) <span class="sc">+</span> </span>
<span id="cb39-14"><a href="#cb39-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb39-15"><a href="#cb39-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Observations from mtcars on the predicted probability surface"</span></span>
<span id="cb39-16"><a href="#cb39-16" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb39-17"><a href="#cb39-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(</span>
<span id="cb39-18"><a href="#cb39-18" aria-hidden="true" tabindex="-1"></a>    <span class="fu">aes</span>(<span class="at">x =</span> hp, <span class="at">y =</span> wt), <span class="at">inherit.aes =</span> <span class="cn">FALSE</span>,</span>
<span id="cb39-19"><a href="#cb39-19" aria-hidden="true" tabindex="-1"></a>    <span class="at">data =</span> mtcars</span>
<span id="cb39-20"><a href="#cb39-20" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-24-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Perhaps a better option, then, would be to calculate an average marginal effect using the observed values, but switching the observations for <code>vs</code> to 1 in one scenario, and 0 in another scenario:</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>predictions_predictors_observed_straight <span class="ot">&lt;-</span> mtcars <span class="sc">|&gt;</span> </span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(hp, wt) <span class="sc">|&gt;</span> </span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">vs =</span> <span class="dv">1</span>)</span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a>predictions_predictors_observed_straight <span class="ot">&lt;-</span> predictions_predictors_observed_straight <span class="sc">|&gt;</span> </span>
<span id="cb40-6"><a href="#cb40-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb40-7"><a href="#cb40-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">p_manual =</span> <span class="fu">predict</span>(mod_logistic_2, <span class="at">type =</span> <span class="st">"response"</span>, <span class="at">newdata =</span> predictions_predictors_observed_straight)</span>
<span id="cb40-8"><a href="#cb40-8" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb40-9"><a href="#cb40-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-10"><a href="#cb40-10" aria-hidden="true" tabindex="-1"></a>predictions_predictors_observed_vshaped <span class="ot">&lt;-</span> mtcars <span class="sc">|&gt;</span> </span>
<span id="cb40-11"><a href="#cb40-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(hp, wt) <span class="sc">|&gt;</span> </span>
<span id="cb40-12"><a href="#cb40-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">vs =</span> <span class="dv">0</span>) </span>
<span id="cb40-13"><a href="#cb40-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-14"><a href="#cb40-14" aria-hidden="true" tabindex="-1"></a>predictions_predictors_observed_vshaped <span class="ot">&lt;-</span> predictions_predictors_observed_vshaped <span class="sc">|&gt;</span> </span>
<span id="cb40-15"><a href="#cb40-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb40-16"><a href="#cb40-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">p_manual =</span> <span class="fu">predict</span>(mod_logistic_2, <span class="at">type =</span> <span class="st">"response"</span>, <span class="at">newdata =</span> predictions_predictors_observed_vshaped)</span>
<span id="cb40-17"><a href="#cb40-17" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb40-18"><a href="#cb40-18" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb40-19"><a href="#cb40-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-20"><a href="#cb40-20" aria-hidden="true" tabindex="-1"></a>predictions_predictors_observed <span class="ot">&lt;-</span> </span>
<span id="cb40-21"><a href="#cb40-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">bind_rows</span>(</span>
<span id="cb40-22"><a href="#cb40-22" aria-hidden="true" tabindex="-1"></a>    predictions_predictors_observed_straight,</span>
<span id="cb40-23"><a href="#cb40-23" aria-hidden="true" tabindex="-1"></a>    predictions_predictors_observed_vshaped</span>
<span id="cb40-24"><a href="#cb40-24" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb40-25"><a href="#cb40-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-26"><a href="#cb40-26" aria-hidden="true" tabindex="-1"></a>predictions_marginal <span class="ot">&lt;-</span> </span>
<span id="cb40-27"><a href="#cb40-27" aria-hidden="true" tabindex="-1"></a>  predictions_predictors_observed <span class="sc">|&gt;</span> </span>
<span id="cb40-28"><a href="#cb40-28" aria-hidden="true" tabindex="-1"></a>    <span class="fu">group_by</span>(hp, wt) <span class="sc">|&gt;</span> </span>
<span id="cb40-29"><a href="#cb40-29" aria-hidden="true" tabindex="-1"></a>    <span class="fu">summarise</span>(</span>
<span id="cb40-30"><a href="#cb40-30" aria-hidden="true" tabindex="-1"></a>      <span class="at">diff_p_manual =</span> p_manual[vs<span class="sc">==</span><span class="dv">1</span>] <span class="sc">-</span> p_manual[vs<span class="sc">==</span><span class="dv">0</span>]</span>
<span id="cb40-31"><a href="#cb40-31" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb40-32"><a href="#cb40-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-33"><a href="#cb40-33" aria-hidden="true" tabindex="-1"></a>predictions_marginal <span class="sc">|&gt;</span> </span>
<span id="cb40-34"><a href="#cb40-34" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> diff_p_manual)) <span class="sc">+</span> </span>
<span id="cb40-35"><a href="#cb40-35" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>() <span class="sc">+</span></span>
<span id="cb40-36"><a href="#cb40-36" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="fu">aes</span>(<span class="at">xintercept =</span> <span class="fu">mean</span>(diff_p_manual)), <span class="at">colour =</span> <span class="st">"red"</span>) <span class="sc">+</span> </span>
<span id="cb40-37"><a href="#cb40-37" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="fu">aes</span>(<span class="at">xintercept =</span> <span class="fu">median</span>(diff_p_manual)), <span class="at">colour =</span> <span class="st">"green"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-25-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>In the above the red line indicates the mean value of these marginal differences, which is <code>-0.12</code>, and the green line the median value of these differences, which is around <code>-0.02</code>. So, even with just these two measures of central tendency, there’s around a six-fold difference in the estimate of ‘the effect’. We can also see there’s a lot of variation, from around nothing (right hand side), to around a 65% reduction (left hand side).</p>
<p>If forced to give a simple answer (to this overly simplistic question), we might plump for the mean for theoretical reasons, and say something like “The effect of a straight engine is to reduce the probability of a manual transmission by around an eighth”. But I’m sure, having seen how much variation there is in these marginal effects, we can agree this ‘around an eighth’ answer, or any single number answer, is likely to be overly reductive.</p>
<p>Hopefully, however, it is more informative than ‘statistically significant and negative’, (the stargazing approach) or ‘up to around 78%’ (the divide-by-four approach).</p>
</section>
<section id="conclusion" class="level3">
<h3 class="anchored" data-anchor-id="conclusion">Conclusion</h3>
<p>Linear regression tends to give a false impression about how straightforward it is to use a model to answer questions of the form “What is the effect of x on y?”. This is because, for linear regression, but few other model specifications, the answer to this question is in the <span class="math inline">\(\beta\)</span> coefficients themselves. For other model specifications, like the logistic regression example above, the correct-but-uninformative answer tends to be “it depends”, and potentially more informative answers tend to require a bit more work to derive and interpret.</p>
</section>
</section>
<section id="page-discussion" class="level2">
<h2 class="anchored" data-anchor-id="page-discussion">Page discussion</h2>
<p>This section of the course has aimed to reintroduce statistics from the perspective of generalised linear models (GLMs), in order to make the following clearer:</p>
<ul>
<li>That linear regression is just one member of a broader ‘family’ of regression models</li>
<li>That all regression models can be thought of as just ‘types’ of GLM, with more in common than divides them</li>
<li>That we can and should aim for <em>substantive significance</em> when using the outputs of GLMs, i.e.&nbsp;use them for prediction and simulation rather than focus on whether individual coefficients are ‘statistically significant’ or not.</li>
</ul>
<p>The <a href="../../../pages/main-course/likelihood-and-simulation-theory/index.html">next section</a> of the course delves further into the fundamentals of model fitting and statistical inference, including likelihood theory.</p>



</section>


<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body hanging-indent" role="list">
<div id="ref-KinTomWit00" class="csl-entry" role="listitem">
King, Gary, Michael Tomz, and Jason Wittenberg. 2000. <span>“Making the Most of Statistical Analyses: Improving Interpretation and Presentation.”</span> <em>American Journal of Political Science</em> 44: 341355. <a href="http://gking.harvard.edu/files/abs/making-abs.shtml">http://gking.harvard.edu/files/abs/making-abs.shtml</a>.
</div>
</div></section><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Footnotes</h2>

<ol>
<li id="fn1"><p>Note here I’m using <span class="math inline">\(x_j\)</span>, not <span class="math inline">\(x_i\)</span>, and that <span class="math inline">\(X\beta\)</span> is shorthand for <span class="math inline">\(\beta_0 + \beta_1 x_1 + \beta_2 x_2 + \beta_3 x_3\)</span> and so on. In using the <span class="math inline">\(j\)</span> suffix, I’m referring to just one of the specific <span class="math inline">\(x\)</span> values, <span class="math inline">\(x_1\)</span>, <span class="math inline">\(x_2\)</span>, <span class="math inline">\(x_3\)</span>, which is equivalent to selecting one of the <em>columns in</em> <span class="math inline">\(X\)</span>. By contrast <span class="math inline">\(i\)</span> should be considered shorthand for selection of one of the <em>rows of</em> <span class="math inline">\(X\)</span>, i.e.&nbsp;one of the series of observations that goes into the dataset <span class="math inline">\(D\)</span>.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>Note here I’m using <span class="math inline">\(x_j\)</span>, not <span class="math inline">\(x_i\)</span>, and that <span class="math inline">\(X\beta\)</span> is shorthand for <span class="math inline">\(\beta_0 + \beta_1 x_1 + \beta_2 x_2 + \beta_3 x_3\)</span> and so on. In using the <span class="math inline">\(j\)</span> suffix, I’m referring to just one of the specific <span class="math inline">\(x\)</span> values, <span class="math inline">\(x_1\)</span>, <span class="math inline">\(x_2\)</span>, <span class="math inline">\(x_3\)</span>, which is equivalent to selecting one of the <em>columns in</em> <span class="math inline">\(X\)</span>. By contrast <span class="math inline">\(i\)</span> should be considered shorthand for selection of one of the <em>rows of</em> <span class="math inline">\(X\)</span>, i.e.&nbsp;one of the series of observations that goes into the dataset <span class="math inline">\(D\)</span>.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p><span class="math inline">\(E(.)\)</span> is the expectation operator, and <span class="math inline">\(|\)</span> indicates a condition. So, the two terms mean, respectively, <em>what is the expected value of the outcome if the variable of interest is ‘switched on’?</em>, and <em>what is the expected value of the outcome if the variable of interest is ‘switched off’?</em><a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn4"><p>The logistic function maps any real number <code>z</code> onto the value range 0 to 1. <code>z</code> is <span class="math inline">\(X\beta\)</span>, which in non-matrix notation is equivalent to a sum of products <span class="math inline">\(\sum_{k=0}^{K}x_k\beta_k\)</span> (where, usually, <span class="math inline">\(x_0\)</span> is 1, i.e.&nbsp;the intercept term). Another way of expressing this would be something like <span class="math inline">\(\sum_{k \in S}x_k\beta_k\)</span> where by default <span class="math inline">\(S = \{0, 1, 2, ..., K\}\)</span>. We can instead imagine partitioning out <span class="math inline">\(S = \{S^{-J}, S^{J}\}\)</span> where the superscript <span class="math inline">\(J\)</span> indicates the Jth variable, and <span class="math inline">\(-J\)</span> indicates everything in <span class="math inline">\(S\)</span> <em>apart from</em> the Jth variable. Where J is a discrete variable, the effect of J on <span class="math inline">\(P(Y=1)\)</span> is <span class="math inline">\(logistic({\sum_{k \in S^{-J}}x_k\beta_k + \beta_J}) - logistic({\sum_{k \in S^{-J}}x_k\beta_k})\)</span>, where <span class="math inline">\(logistic(z) = \frac{1}{1 + e^{-z}}\)</span>. The marginal effect of the <span class="math inline">\(\beta_J\)</span> coefficient thus depends on the other term <span class="math inline">\(\sum_{k \in S^{-J}}x_k\beta_k\)</span>. Where this other term is set to 0 the marginal effect of <span class="math inline">\(\beta_J\)</span> becomes <span class="math inline">\(logistic(\beta_J) - logistic(0)\)</span>. According to p.82 of <a href="https://vulstats.ucsd.edu/pdf/Gelman.ch-05.logistic-regression.pdf">this chapter by Gelman</a> we can equivalently ask the question ‘what is the first derivative of the logistic regression with respect to <span class="math inline">\(\beta\)</span>?’. Asking more about this to Wolfram Alpha we get <a href="https://www.wolframalpha.com/input?i=what+is+the+the+maximum+absolute+value+of+the+derivative+of+1+%2F+%281+%2B+exp%28beta%29%29+with+respect+to+beta%3F">this page of information</a>, and scrolling down to the section on the global minimum we indeed get an absolute value of <span class="math inline">\(\frac{1}{4}\)</span>, so the maximum change in <span class="math inline">\(P(Y=1)\)</span> given a unit change in <span class="math inline">\(\beta\)</span> is indeed one quarter of the value of <span class="math inline">\(\beta\)</span>, hence why the ‘divide-by-four’ heuristic ‘works’. This isn’t quite a full derivation, but more explanation than I was planning for a footnote! In general, it’s better just to remember ‘divide-by-four’ than go down the rabbit warren of derivation each time! (As I’ve just learned, to my cost, writing this footnote!)<a href="#fnref4" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn5"><p>We should <em>always</em> expect the absolute value of a coefficient for a discrete variable to be less than four, for this reason.<a href="#fnref5" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn6"><p>The lower bound for the marginal effect of a discrete variable, or any variable, is zero. This is when the absolute value of the sum of the product of the other variables is infinite.<a href="#fnref6" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn7"><p>Or the base R <code>expand.grid</code> function<a href="#fnref7" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  let localAlternateSentinel = 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>