project:
  type: website

website:
  title: "JonStats"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - sidebar:main-course
      - sidebar:extra-courses

  sidebar:
    - id: main-course
      title: "Main Course: Statistical Inference and Simulation"
      contents:
        - href: pages/main-course/statistics-as-circuits/index.qmd
          text: "(0) Statistics as Circuit Boards"
        - href: pages/main-course/intro-to-glms/index.qmd
          text: "(1) Intro to GLMs"
        - href: pages/main-course/likelihood-and-simulation-theory/index.qmd
          text: "(2) Likelihood and Simulation Theory"
        - href: pages/main-course/complete-simulation-example/index.qmd
          text: "(3) Complete Simulation Example"

    - id: extra-courses
      title: "Supplementary Courses"
      contents:
        - href: pages/extra-courses/causal-inference/index.qmd
          text: "Causal Inference"
        - href: pages/extra-courses/time-series/index.qmd
          text: "Time Series"
        - href: pages/extra-courses/hacker-stats/index.qmd
          text: "Hacker Stats"




format:
  html:
    theme: 
      light: cosmo
      dark: slate
    css: styles.css
    toc: true


